<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SystemERP.DAL\SystemERP.DAL.csproj" />
    <ProjectReference Include="..\SystemERP.DTO\SystemERP.DTO.csproj" />
    <ProjectReference Include="..\SystemERP.Model\SystemERP.Model.csproj" />
    <ProjectReference Include="..\SystemERP.Utility\SystemERP.Utility.csproj" />
  </ItemGroup>

</Project>
